# Generated by Django 6.0 on 2026-01-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('experience', models.IntegerField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='doctors/documents/')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
