# Generated by Django 6.0 on 2026-01-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/images/'),
        ),
    ]
