# Generated by Django 6.0 on 2026-01-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='doctors/docs/'),
        ),
    ]
