# Generated by Django 6.0 on 2026-01-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='chatthread',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
